services:
  wikirego:
    build:
      context: .
      dockerfile: Dockerfile
    image: dannyswat/wikirego:latest
    container_name: wikirego
    ports:
      - "8080:8080"
    volumes:
      - ./server/data:/app/data
      - ./server/media:/app/media
      - ./server/conf:/app/conf
    restart: unless-stopped
